### ISSUE TITLE
UI Implementation #1 - LandingPage, Lobby, Tournement Creation

### ISSUE THREAD

**Issue by vidurathegeek** [the-ai-team/razor#8]
### Description
- [x] Prepare a design document for the UI of LandingPage
- [x] Prepare a design document for the UI of the Lobby
- [x] Prepare a design document for the UI of the TournementCreation

**Comment by supunTE** [comment]
Designing - https://github.com/the-ai-team/razor/issues/23

**Comment by supunTE** [comment]
Designing task is completed.
